	Adding nVidia Cuda Toolkit 11.8
	Adding nVidia cuDNN 8.6 (.0.163)
WARNING (pytensor.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
Traceback (most recent call last):
  File "main.py", line 76, in <module>
    trace = posterior_inference_mcmc(Xu_noise, jnp.eye(2)*prior_var, param_iter, Xu_fixed, Xf, Y)
  File "/local/233993/include/mcmc_posterior.py", line 34, in posterior_inference_mcmc
    z_uncertain_list.append(pm.MvNormal('z_uncertain',mu=prior_mean[num_sample,:],cov=prior_cov))
  File "/home/yanw/.conda/envs/uncertain/lib/python3.8/site-packages/pymc/distributions/distribution.py", line 310, in __new__
    rv_out = model.register_rv(
  File "/home/yanw/.conda/envs/uncertain/lib/python3.8/site-packages/pymc/model.py", line 1290, in register_rv
    self.add_named_variable(rv_var, dims)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.8/site-packages/pymc/model.py", line 1468, in add_named_variable
    raise ValueError(f"Variable name {var.name} already exists.")
ValueError: Variable name z_uncertain already exists.
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[28750,1],0]
  Exit code:    1
--------------------------------------------------------------------------
cp: missing destination file operand after '*.png/home/yanw/uncertain/results/figures/0906'
Try 'cp --help' for more information.
cp: missing destination file operand after '/home/yanw/uncertain'
Try 'cp --help' for more information.
mv: cannot stat '*.log': No such file or directory
