Traceback (most recent call last):
  File "/local/293707/main.py", line 196, in <module>
    mse = mean_squared_error(y_train, y_pred)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/sklearn/utils/_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/sklearn/metrics/_regression.py", line 506, in mean_squared_error
    y_type, y_true, y_pred, multioutput = _check_reg_targets(
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/sklearn/metrics/_regression.py", line 111, in _check_reg_targets
    check_consistent_length(y_true, y_pred)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/sklearn/utils/validation.py", line 460, in check_consistent_length
    raise ValueError(
ValueError: Found input variables with inconsistent numbers of samples: [25, 15]
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[6544,1],0]
  Exit code:    1
--------------------------------------------------------------------------
cp: missing destination file operand after '*.png/home/yanw/uncertain/results/figures/0617'
Try 'cp --help' for more information.
cp: missing destination file operand after '/home/yanw/uncertain'
Try 'cp --help' for more information.
mv: cannot stat '*.log': No such file or directory
