Traceback (most recent call last):
  File "/local/293759/main.py", line 206, in <module>
    errors = (y_test - y_pred) ** 2
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/numpy/array_methods.py", line 264, in deferring_binary_op
    return binary_op(*args)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 179, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/pjit.py", line 248, in cache_miss
    outs, out_flat, out_tree, args_flat, jaxpr, attrs_tracked = _python_pjit_helper(
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/pjit.py", line 136, in _python_pjit_helper
    infer_params_fn(*args, **kwargs)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/api.py", line 325, in infer_params
    return pjit.common_infer_params(pjit_info_args, *args, **kwargs)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/pjit.py", line 495, in common_infer_params
    jaxpr, consts, out_shardings, out_layouts_flat, attrs_tracked = _pjit_jaxpr(
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/pjit.py", line 1150, in _pjit_jaxpr
    jaxpr, final_consts, out_type, attrs_tracked = _create_pjit_jaxpr(
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/linear_util.py", line 350, in memoized_fun
    ans = call(fun, *args)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/pjit.py", line 1089, in _create_pjit_jaxpr
    jaxpr, global_out_avals, consts, attrs_tracked = pe.trace_to_jaxpr_dynamic(
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/profiler.py", line 336, in wrapper
    return func(*args, **kwargs)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/interpreters/partial_eval.py", line 2314, in trace_to_jaxpr_dynamic
    jaxpr, out_avals, consts, attrs_tracked = trace_to_subjaxpr_dynamic(
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/interpreters/partial_eval.py", line 2336, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers_)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/linear_util.py", line 192, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/numpy/ufuncs.py", line 85, in <lambda>
    fn = lambda x1, x2, /: lax_fn(*promote_args(numpy_fn.__name__, x1, x2))
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/lax/lax.py", line 423, in sub
    return sub_p.bind(x, y)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/core.py", line 420, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/core.py", line 423, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/interpreters/partial_eval.py", line 2008, in process_primitive
    return self.default_process_primitive(primitive, tracers, params)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/interpreters/partial_eval.py", line 2012, in default_process_primitive
    out_avals, effects = primitive.abstract_eval(*avals, **params)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/core.py", line 456, in abstract_eval_
    return abstract_eval(*args, **kwargs), no_effects
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/lax/utils.py", line 60, in standard_abstract_eval
    return core.ShapedArray(shape_rule(*avals, **kwargs),
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/lax/lax.py", line 1637, in broadcasting_shape_rule
    raise TypeError(f'{name} got incompatible shapes for broadcasting: '
TypeError: sub got incompatible shapes for broadcasting: (10, 1), (30, 1).
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[50073,1],0]
  Exit code:    1
--------------------------------------------------------------------------
cp: missing destination file operand after '*.png/home/yanw/uncertain/results/figures/0617'
Try 'cp --help' for more information.
cp: missing destination file operand after '/home/yanw/uncertain'
Try 'cp --help' for more information.
