/local/295103/include/mcmc_posterior.py:99: UserWarning: There are not enough devices to run parallel chains: expected 2 but got 1. Chains will be drawn sequentially. If you are running MCMC in CPU, consider using `numpyro.set_host_device_count(2)` at the beginning of your program. You can double-check how many devices are available in your system using `jax.local_device_count()`.
  mcmc = MCMC(kernel, num_warmup=num_warmup, num_samples=num_samples,num_chains=2, chain_method='parallel', progress_bar=False)
Traceback (most recent call last):
  File "/local/295103/main.py", line 116, in <module>
    mcmc = run_mcmc(Xu_fixed, Xf, Y, Xu_noise, prior_var*jnp.eye(2), param_iter, num_samples=num_mcmc,
  File "/local/295103/include/mcmc_posterior.py", line 100, in run_mcmc
    mcmc.run(rng_key, Xfz, Xfg, Y_data, prior_mean, prior_cov, init_params)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/numpyro/infer/mcmc.py", line 670, in run
    states, last_state = _laxmap(partial_map_fn, map_args)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/numpyro/infer/mcmc.py", line 176, in _laxmap
    ys.append(f(x))
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/numpyro/infer/mcmc.py", line 462, in _single_chain_mcmc
    collect_vals = fori_collect(
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/numpyro/util.py", line 347, in fori_collect
    last_val, collection, _, _ = fori_loop(
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/numpyro/util.py", line 141, in fori_loop
    return lax.fori_loop(lower, upper, body_fun, init_val)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 179, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/lax/control_flow/loops.py", line 1995, in fori_loop
    (_, result), _ = scan(
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 179, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/lax/control_flow/loops.py", line 260, in scan
    init_flat, carry_avals, carry_avals_out, init_tree, *rest = _create_jaxpr(init)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/lax/control_flow/loops.py", line 245, in _create_jaxpr
    jaxpr, consts, out_tree, attrs_tracked = _initial_style_jaxpr_attrs(
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/lax/control_flow/common.py", line 74, in _initial_style_jaxpr_attrs
    jaxpr, consts, out_tree, attrs_tracked = _initial_style_open_jaxpr(
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/lax/control_flow/common.py", line 60, in _initial_style_open_jaxpr
    jaxpr, _, consts, attrs_tracked = pe.trace_to_jaxpr_dynamic(
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/profiler.py", line 336, in wrapper
    return func(*args, **kwargs)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/interpreters/partial_eval.py", line 2314, in trace_to_jaxpr_dynamic
    jaxpr, out_avals, consts, attrs_tracked = trace_to_subjaxpr_dynamic(
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/interpreters/partial_eval.py", line 2336, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers_)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/linear_util.py", line 192, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/jax/_src/lax/control_flow/loops.py", line 1885, in scanned_fun
    return (i + 1, body_fun()(i, x)), None
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/numpyro/util.py", line 332, in _body_fn
    val = body_fun(val)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/numpyro/infer/mcmc.py", line 188, in _sample_fn_nojit_args
    return (sampler.sample(state[0], args, kwargs),)
  File "/local/295103/include/mcmc_posterior.py", line 78, in sample
    u_proposal = dist.Normal(u, self.step_size).sample(key_proposal)
  File "/home/yanw/.conda/envs/uncertain/lib/python3.9/site-packages/numpyro/distributions/continuous.py", line 2093, in sample
    return self.loc + eps * self.scale
TypeError: unsupported operand type(s) for +: 'NoneType' and 'DynamicJaxprTracer'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[59790,1],0]
  Exit code:    1
--------------------------------------------------------------------------
cp: missing destination file operand after '*.png/home/yanw/uncertain/results/figures/0622'
Try 'cp --help' for more information.
cp: missing destination file operand after '/home/yanw/uncertain'
Try 'cp --help' for more information.
