	Adding nVidia Cuda Toolkit 11.8
	Adding nVidia cuDNN 8.6 (.0.163)
WARNING (pytensor.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
Traceback (most recent call last):
  File "main.py", line 81, in <module>
    trace = posterior_inference_mcmc(Xu_noise, jnp.eye(2)*prior_var, param_iter, Xu_fixed, Xf, Y)  #TODO: Y
  File "/local/236194/include/mcmc_posterior.py", line 47, in posterior_inference_mcmc
    K = compute_K(init_params, z_uncertain, Xfz, Xfg)
  File "/local/236194/include/mcmc_posterior.py", line 12, in compute_K
    zz_uu = heat_equation_kuu_noise(Xuz, Xuz, params)
  File "/home/yanw/.local/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/yanw/.local/lib/python3.8/site-packages/jax/_src/pjit.py", line 250, in cache_miss
    outs, out_flat, out_tree, args_flat, jaxpr = _python_pjit_helper(
  File "/home/yanw/.local/lib/python3.8/site-packages/jax/_src/pjit.py", line 158, in _python_pjit_helper
    args_flat, _, params, in_tree, out_tree, _ = infer_params_fn(
  File "/home/yanw/.local/lib/python3.8/site-packages/jax/_src/api.py", line 306, in infer_params
    return pjit.common_infer_params(pjit_info_args, *args, **kwargs)
  File "/home/yanw/.local/lib/python3.8/site-packages/jax/_src/pjit.py", line 491, in common_infer_params
    avals.append(shaped_abstractify(a))
  File "/home/yanw/.local/lib/python3.8/site-packages/jax/_src/api_util.py", line 563, in shaped_abstractify
    return _shaped_abstractify_handlers[type(x)](x)
  File "/home/yanw/.local/lib/python3.8/site-packages/jax/_src/api_util.py", line 575, in _numpy_array_abstractify
    dtypes.check_valid_dtype(dtype)
  File "/home/yanw/.local/lib/python3.8/site-packages/jax/_src/dtypes.py", line 513, in check_valid_dtype
    raise TypeError(f"Dtype {dtype} is not a valid JAX array "
jax._src.traceback_util.UnfilteredStackTrace: TypeError: Dtype object is not a valid JAX array type. Only arrays of numeric types are supported by JAX.

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 81, in <module>
    trace = posterior_inference_mcmc(Xu_noise, jnp.eye(2)*prior_var, param_iter, Xu_fixed, Xf, Y)  #TODO: Y
  File "/local/236194/include/mcmc_posterior.py", line 47, in posterior_inference_mcmc
    K = compute_K(init_params, z_uncertain, Xfz, Xfg)
  File "/local/236194/include/mcmc_posterior.py", line 12, in compute_K
    zz_uu = heat_equation_kuu_noise(Xuz, Xuz, params)
TypeError: Dtype object is not a valid JAX array type. Only arrays of numeric types are supported by JAX.
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[64713,1],0]
  Exit code:    1
--------------------------------------------------------------------------
cp: missing destination file operand after '*.png/home/yanw/uncertain/results/figures/0920'
Try 'cp --help' for more information.
cp: missing destination file operand after '/home/yanw/uncertain'
Try 'cp --help' for more information.
